<div align="center">

# <span style="color:green"> <ins> Classification of Iris Species with Logistic Regression <ins></span>
## <span style="color:orangered">(Achieved 100% accuracy)</span>

<div align="center" width="50">
    <br>
    <br>
    <br>

</div>

In [61]:
# Importing the libraries and Dataset
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.datasets import load_iris            # importing iris dataset
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
%matplotlib inline

## Exploring Data

In [15]:
iris = load_iris()

In [20]:
dataset= pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [21]:
dataset.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [22]:
dataset['target'].value_counts()

2.0    50
1.0    50
0.0    50
Name: target, dtype: int64

In [23]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal length (cm)    150 non-null float64
sepal width (cm)     150 non-null float64
petal length (cm)    150 non-null float64
petal width (cm)     150 non-null float64
target               150 non-null float64
dtypes: float64(5)
memory usage: 6.0 KB


In [24]:
dataset.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [25]:
dataset.corr()[['target']].sort_values(by='target',ascending=False)

target
target             1.000000
petal width (cm)   0.956547
petal length (cm)  0.949035
sepal length (cm)  0.782561
sepal width (cm)  -0.426658

In [26]:
x_train=dataset.drop('target',axis=1)
y_train=dataset[['target']]

In [29]:
x_train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [30]:
y_train.head()

target
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0

# Splitting the dataset into the Training set and Test set

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x_train, y_train, test_size=0.2, random_state=0)

In [55]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(96, 4)
(24, 4)
(96, 1)
(24, 1)


## Training with Logistic Regression

In [56]:
model_logistic=LogisticRegression(C=112,max_iter=50)

In [57]:
model_logistic.fit(x_train,y_train)

/home/dheeraj/my_projects/my_project_env/lib/python3.6/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/dheeraj/my_projects/my_project_env/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=112, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=50,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Evaluating model

In [58]:
y_predict=model_logistic.predict(x_test)

In [59]:
print("Cofusion matrix is: \n {} ".format(confusion_matrix(y_test,y_predict)))
print("\n Accuracy of the model is: {} ".format(accuracy_score(y_test,y_predict)*100))

Cofusion matrix is: 
 [[11  0  0]
 [ 0  5  0]
 [ 0  0  8]] 

 Accuracy of the model is: 100.0 
