<div align="center">

# <span style="color:green"> <ins> Classification of Iris Species with Logistic Regression <ins></span>
## <span style="color:orangered">(Achieved 100% accuracy)</span>

<div align="center" width="50">
    <br>
    <br>
    <br>

</div>

In [1]:
# Importing the libraries and Dataset
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.datasets import load_iris            # importing iris dataset
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
%matplotlib inline

## Exploring Data

In [2]:
iris = load_iris()

In [3]:
dataset= pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [4]:
dataset.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [5]:
dataset['target'].value_counts()

2.0    50
1.0    50
0.0    50
Name: target, dtype: int64

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    float64
dtypes: float64(5)
memory usage: 6.0 KB


In [7]:
dataset.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [8]:
dataset.corr()[['target']].sort_values(by='target',ascending=False)

target
target             1.000000
petal width (cm)   0.956547
petal length (cm)  0.949035
sepal length (cm)  0.782561
sepal width (cm)  -0.426658

In [9]:
x_train=dataset.drop('target',axis=1)
y_train=dataset[['target']]

In [10]:
x_train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [11]:
y_train.head()

target
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0

# Splitting the dataset into the Training set and Test set

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x_train, y_train, test_size=0.2, random_state=0)

In [13]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120, 1)
(30, 1)


In [14]:
from lazypredict.Supervised import LazyRegressor

/home/dheeraj/my_projects/my_project_env/lib/python3.6/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)


In [15]:
regr=LazyRegressor(verbose=0,predictions=True)

In [16]:
import time
start_time_2=time.time()
models_r,predictions_r=regr.fit(x_train, x_test, y_train, y_test)
end_time_2=time.time()

100%|██████████| 43/43 [00:05<00:00,  7.98it/s]


Exception: Data must be 1-dimensional

## Training with Logistic Regression

In [17]:
model_logistic=LogisticRegression(C=112,max_iter=50)

In [18]:
model_logistic.fit(x_train,y_train)

LogisticRegression(C=112, max_iter=50)

## Evaluating model

In [19]:
y_predict=model_logistic.predict(x_test)

In [20]:
print("Cofusion matrix is: \n {} ".format(confusion_matrix(y_test,y_predict)))
print("\n Accuracy of the model is: {} ".format(accuracy_score(y_test,y_predict)*100))

Cofusion matrix is: 
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]] 

 Accuracy of the model is: 100.0 
