In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
train = pd.read_csv("/home/dheeraj/my_projects/my_project_env/practice/EDA-FeatureEng-FeatureSelection-Prediction/Predictions with Deep Learning models/Stock Price Prediction with RNN/Google_Stock_Price_Train.csv")

In [4]:
train.tail()

Date    Open    High     Low   Close     Volume
1253  12/23/2016  790.90  792.74  787.28  789.91    623,400
1254  12/27/2016  790.68  797.86  787.66  791.55    789,100
1255  12/28/2016  793.70  794.23  783.20  785.05  1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79    744,300
1257  12/30/2016  782.75  782.78  770.41  771.82  1,770,000

In [5]:
train_set = train.iloc[:, 1:2]
train_set.head()

Open
0  325.25
1  331.27
2  329.83
3  328.34
4  322.04

In [6]:
len(train_set)

1258

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
scaler = MinMaxScaler(feature_range=(0,1))
train_set_scaled = scaler.fit_transform(train_set)

In [9]:
print(train_set_scaled)

[[0.08581368]
 [0.09701243]
 [0.09433366]
 ...
 [0.95725128]
 [0.93796041]
 [0.93688146]]


In [10]:
x_train = []
y_train = []
for i in range(60, len(train_set_scaled)):
    x_train.append(train_set_scaled[i-60:i, 0])
    y_train.append(train_set_scaled[i , 0])

In [11]:
# y_train

In [12]:
# x_train

In [13]:
x_train, y_train = np.array(x_train), np.array(y_train)

In [14]:
print(x_train)

[[0.08581368 0.09701243 0.09433366 ... 0.07846566 0.08034452 0.08497656]
 [0.09701243 0.09433366 0.09156187 ... 0.08034452 0.08497656 0.08627874]
 [0.09433366 0.09156187 0.07984225 ... 0.08497656 0.08627874 0.08471612]
 ...
 [0.92106928 0.92438053 0.93048218 ... 0.95475854 0.95204256 0.95163331]
 [0.92438053 0.93048218 0.9299055  ... 0.95204256 0.95163331 0.95725128]
 [0.93048218 0.9299055  0.93113327 ... 0.95163331 0.95725128 0.93796041]]


In [29]:
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))

In [30]:
x_train.shape

(1198, 60, 1)

In [31]:
import keras

In [32]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [33]:
regressor = Sequential()

In [34]:
regressor.add(LSTM(units=50, return_sequences=True, input_shape=(x_train.shape[1], 1)))
regressor.add(Dropout(0.2))

In [35]:
regressor.add(LSTM(units=50, return_sequences=True))
regressor.add(Dropout(0.2))

In [36]:
regressor.add(LSTM(units=50, return_sequences=True))
regressor.add(Dropout(0.2))

In [37]:
regressor.add(LSTM(units=50))
regressor.add(Dropout(0.2))

In [38]:
regressor.add(Dense(units=1))

In [45]:
regressor.compile(loss='mean_squared_error', optimizer='Adam')


In [47]:
regressor.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_6 (LSTM)                (None, 60, 50)            10400     
_________________________________________________________________
dropout_6 (Dropout)          (None, 60, 50)            0         
_________________________________________________________________
lstm_7 (LSTM)                (None, 60, 50)            20200     
_________________________________________________________________
dropout_7 (Dropout)          (None, 60, 50)            0         
_________________________________________________________________
lstm_8 (LSTM)                (None, 60, 50)            20200     
_________________________________________________________________
dropout_8 (Dropout)          (None, 60, 50)            0         
_________________________________________________________________
lstm_9 (LSTM)                (None, 50)               

In [46]:
regressor.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
1198/1198 [==============================] - 11s 9ms/step - loss: 0.0057
Epoch 2/10
1198/1198 [==============================] - 8s 6ms/step - loss: 0.0035
Epoch 3/10
1198/1198 [==============================] - 7s 6ms/step - loss: 0.0036
Epoch 4/10
1198/1198 [==============================] - 6s 5ms/step - loss: 0.0032
Epoch 5/10
1198/1198 [==============================] - 6s 5ms/step - loss: 0.0031
Epoch 6/10
1198/1198 [==============================] - 6s 5ms/step - loss: 0.0029
Epoch 7/10
1198/1198 [==============================] - 6s 5ms/step - loss: 0.0030
Epoch 8/10
1198/1198 [==============================] - 5s 5ms/step - loss: 0.0035
Epoch 9/10
1198/1198 [==============================] - 6s 5ms/step - loss: 0.0028
Epoch 10/10
1198/1198 [==============================] - 6s 5ms/step - loss: 0.0030


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_6 (LSTM)                (None, 60, 50)            10400     
_________________________________________________________________
dropout_6 (Dropout)          (None, 60, 50)            0         
_________________________________________________________________
lstm_7 (LSTM)                (None, 60, 50)            20200     
_________________________________________________________________
dropout_7 (Dropout)          (None, 60, 50)            0         
_________________________________________________________________
lstm_8 (LSTM)                (None, 60, 50)            20200     
_________________________________________________________________
dropout_8 (Dropout)          (None, 60, 50)            0         
_________________________________________________________________
lstm_9 (LSTM)                (None, 50)               

In [48]:
test = pd.read_csv("/home/dheeraj/my_projects/my_project_env/practice/EDA-FeatureEng-FeatureSelection-Prediction/Predictions with Deep Learning models/Stock Price Prediction with RNN/Google_Stock_Price_Test.csv")

In [49]:
test.head()

Date    Open    High     Low   Close     Volume
0  1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1  1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2  1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3  1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4  1/9/2017  806.40  809.97  802.83  806.65  1,272,400

In [ ]:
real_stock_price = df.iloc[:,]

In [ ]:
df_total = pd.concat((train, test))